[build]
  ignore = "/bin/false"
  base = ".massivewikibuilder/massivewikibuilder"
  publish = "../output"
  command = "./mwb.py -c ../mwb.yaml -w ../.. -o ../output -t ../this-wiki-themes/dolce --lunr --commits"

[build.environment]
  PYTHON_VERSION = "3.8"
