[build]
  ignore = "/bin/false"
  base = ".nxc"
  publish = "./output"
  command = "nxc build -i .. -o ./output --lunr --commits && cat $NETLIFY_BUILD_BASE/cache/.cask/.git/config"

[build.environment]
  PYTHON_VERSION = "3.8"
