[build]
  ignore = "/bin/false"
  base = ".nxc"
  publish = "./output"
  command = "nxc build -i .. -o ./output --lunr --commits $$ echo $NETLIFY_CACHE_DIR"

[build.environment]
  PYTHON_VERSION = "3.8"
