[build]
  ignore = "/bin/false"
  base = ".nxc"
  publish = "./output"
  command = "nxc build -i .. -o ./output --lunr --commits && ls -l $NETLIFY_BUILD_BASE/repo"

[build.environment]
  PYTHON_VERSION = "3.8"
